### ISSUE TITLE
swift package generate-xcodeproj went wrong!

### ISSUE THREAD

**Issue by scauos** [milanstevanovic/Bookshelf#1]
should change the package 

import PackageDescription

let package = Package(
    name: "BookshelfServer",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: **1**),
        .Package(url: "https://github.com/apple/swift-protobuf.git", Version(0,9,24)),
        ]
)

because the The dependency graph could not be satisfied. The package (https://github.com/vapor/vapor.git) with version tag in range (1.0.0..<1.0.9223372036854775807) is not found. Found tags ([1.1.1, 1.1.2, 1.1.3])

**Comment by milanstevanovic** [comment]
Actually ".Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 0)" is working for me.
And in the official Vapor tutorial, it is still at this version.
For me, everything is working on macOS.
